### ISSUE TITLE
The instance we're trying to create can't use the ami store root device it seems

### ISSUE THREAD

**Issue by scederqv** [gerhalt/mining-camp#9]
Autoscaling group error:

Placing Spot instance request. Status Reason: AMI 'ami-0d7fbe2d96677967f' with an instance-store root device is not supported for the instance type 'i3.large'. Placing Spot instance request failed.

Also, this gave errors so I removed it.

```
--- a/terraform/s3.tf
+++ b/terraform/s3.tf
@@ -16,10 +16,6 @@ resource "aws_s3_bucket" "minecraft" {
     id      = "backup pruning"
     enabled = true

-    tags {
-      "backup"    = "old"
-    }
-
     expiration {
       days = 3
     }
```

**Comment by gerhalt** [comment]
I'll take a look. Based on a quick lookup I would think that AMI would be fine.

With regards to the second terraform issue, what version of Terraform are you using?

**Comment by scederqv** [comment]
I just installed it so I assume it's the latest: 0.12.3

Thanks!

**Comment by scederqv** [comment]
And about the tag thing, first it complains about the quotes around the key, and if you remove those it'll complain that you shouldn't have any tags in that spot. Minor thing.

**Comment by gerhalt** [comment]
Took a look. I don't see that AMI in the public images list in my console, oddly enough. Where did that AMI ID come from?

The tags issue might just be a syntax problem. The current docs' examples make it look like there ought to be a '=' after the tags, so that might do the trick. See https://www.terraform.io/docs/providers/aws/r/s3_bucket.html. It's really just used for lifecycle rules so old backups can be automatically deleted and not clog up your S3 bucket.

**Comment by nikhiljha** [comment]
The tags issue is resolved by adding an `=`. Also, AMI IDs are different per region right? Wenoc might be using a different region than you are.

**Comment by gerhalt** [comment]
Sounds right. The tags issue is a small thing, I'll post a PR for that when I have a spare minute to test it.

**Comment by gerhalt** [comment]
@Wenoc any update with regards to the AMI question? Otherwise I'll close this after addressing the tags problem.
